name: npm-release
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        run: npm i pnpm -g

      - name: install dependencies
        run: pnpm i

      - name: linting
        run: |
          pnpm lint
          pnpm lint:types

      - name: unit tests
        run: pnpm test:ci

      - name: test coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage
          if-no-files-found: error
        
      - name: build
        run: pnpm build

      - name: build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist
          if-no-files-found: error

      - name: publish
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
